name: Playwright Tests

on:
  push:
    branches: [ main, master, '**' ]
  pull_request:
    branches: [ main, master ]

jobs:
  type-check-and-lint:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Node JS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      - name: Run type check
        run: npm run type-check

      - name: Run lint
        run: npm run lint

  playwright-tests:
    needs: [type-check-and-lint]
    timeout-minutes: 10
    env:
      WEB_URL: ${{ secrets.WEB_URL }}
      API_URL: ${{ secrets.API_URL }}
      USER_EMAIL: ${{ secrets.USER_EMAIL }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      USER_NAME: ${{ secrets.USER_NAME }}
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      ADMIN_NAME: ${{ secrets.ADMIN_NAME }}
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-noble
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Node JS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: |
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --project=chromium

      - name: Upload Playwright HTML report to GitHub Actions Artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: Playwright HTML report
          path: playwright-report/
          retention-days: 3
