name: Playwright Tests Parametrize

on:
  workflow_dispatch:
    inputs:
      baseUrl:
        description: ''
        required: true
        default: 'https://practicesoftwaretesting.com'
      apiUrl:
        description: ''
        required: false
        default: 'https://api.practicesoftwaretesting.com'
      headless:
        description: ''
        required: false
        type: choice
        options:
          - 'true'
          - 'false'
      maxWorkers:
        description: ''
        required: false
        default: '80%'
      project:
        description: ''
        required: true
        type: choice
        options:
          - 'chromium-regression'
          - 'chromium-smoke'
          - 'safari-regression'
          - 'api'

jobs:
  playwright-tests-parametrize:
    timeout-minutes: 10
    env:
      WEB_URL: ${{ github.event.inputs.baseUrl }}
      API_URL: ${{ github.event.inputs.apiUrl }}
      HEADLESS: ${{ github.event.inputs.headless }}
      MAX_WORKERS: ${{ github.event.inputs.maxWorkers }}
      USER_EMAIL: ${{ secrets.USER_EMAIL }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      USER_NAME: ${{ secrets.USER_NAME }}
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      ADMIN_NAME: ${{ secrets.ADMIN_NAME }}
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-noble
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Node JS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: |
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          xvfb-run npx playwright test -c playwright.config.ts --project=${{ github.event.inputs.project }}

      - name: Upload Playwright HTML report to GitHub Actions Artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: Playwright HTML report
          path: playwright-report/
          retention-days: 3
